spring:
  datasource:
    url: "${SPRING_DATABASE_URL}"
    username: "${SPRING_DATABASE_USERNAME}"
    password: "${SPRING_DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true


server:
  port: 8080

app:
  pagination:
    max-page-size: 100
  security:
    password:
      min-password-length: 8
      pattern: ("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$")
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refreshExpiration: ${JWT_REFRESH_EXPIRATION} # 7 days in milliseconds
logging:
  level:
    org:
      springframework:
        web: DEBUG
